var locations = [
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1304.jpg', coordinates: {x: 694, y: 166}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1332.jpg', coordinates: {x: 685, y: 472}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1358.jpg', coordinates: {x: 954, y: 341}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1319.jpeg', coordinates: {x: 434, y: 251}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1321.jpeg', coordinates: {x: 365, y: 408}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1344.jpeg', coordinates: {x: 849, y: 582}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1357.jpeg', coordinates: {x: 959, y: 364}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1360.jpeg', coordinates: {x: 937, y: 291}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/IMG_1323.jpeg', coordinates: {x: 481, y: 363}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG730.jpeg', coordinates: {x: 600, y: 320}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG732.jpeg', coordinates: {x: 628, y: 294}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG734.jpeg', coordinates: {x: 963, y: 280}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG2061.jpeg', coordinates: {x: 449, y: 374}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG736.jpeg', coordinates: {x: 884, y: 304}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG737.jpeg', coordinates: {x: 834, y: 304}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG738.jpeg', coordinates: {x: 821, y: 273}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG739.jpeg', coordinates: {x: 599, y: 243}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG740.jpeg', coordinates: {x: 634, y: 237}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG741.jpeg', coordinates: {x: 705, y: 248}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG742.jpeg', coordinates: {x: 882, y: 370}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG744.jpeg', coordinates: {x: 897, y: 446}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG746.jpeg', coordinates: {x: 864, y: 467}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG748.jpeg', coordinates: {x: 817, y: 445}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG751.jpeg', coordinates: {x: 790, y: 465}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG752.jpeg', coordinates: {x: 687, y: 410}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG754.jpeg', coordinates: {x: 618, y: 377}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG756.jpeg', coordinates: {x: 548, y: 323}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG2067.jpeg', coordinates: {x: 446, y: 189}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG2068.jpeg', coordinates: {x: 829, y: 262}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG2071.jpeg', coordinates: {x: 725, y: 332}},
    {src: 'https://raw.githubusercontent.com/Jonathanxhu/SHSguessr/main/images/WechatIMG2072.jpeg', coordinates: {x: 462, y: 212}},
    
];
